THINGS = [
  {size: '0.00012',     name_singular: 'ovum',               name_plural: 'ovums'},
  {size: '0.00035',     name_singular: 'ameba',              name_plural: 'amebas'},
  {size: '0.0015',      name_singular: 'flea',               name_plural: 'fleas'},
  {size: '0.0055',      name_singular: 'mosquito',           name_plural: 'mosquitos'},
  {size: '0.01',        name_singular: 'fly',                name_plural: 'flies'},
  {size: '0.085',       name_singular: 'apple',              name_plural: 'apples'},
  {size: '0.12',        name_singular: 'optical disk (CD)',  name_plural: 'optical disks (CDs)'},
  {size: '0.22',        name_singular: 'soccer ball',        name_plural: 'soccer balls'},
  {size: '0.5',         name_singular: 'rabbit',             name_plural: 'rabbits'},
  {size: '1.7',         name_singular: 'human',              name_plural: 'humans'},
  {size: '3.0',         name_singular: 'elephant',           name_plural: 'elephants'},
  {size: '5.0',         name_singular: 'giraffe',            name_plural: 'giraffes'},
  {size: '10',          name_singular: 'London bus',         name_plural: 'London buses'},
  {size: '20.0',        name_singular: 'sphinx',             name_plural: 'sphinxes'},
  {size: '33',          name_singular: 'whale',              name_plural: 'whales'},
  {size: '70',          name_singular: 'Jumbo jet airplane', name_plural: 'Jumbo jet airplanes'},
  {size: '93',          name_singular: 'statue of liberty',  name_plural: 'statues of liberty'},
  {size: '3776',        name_singular: 'mount Fuji',         name_plural: 'mount Fujis'},
  {size: '8848',        name_singular: 'mount Everest',      name_plural: 'mount Everests'},
  {size: '3476000',     name_singular: 'moon',               name_plural: 'moons'},
  {size: '6792000',     name_singular: 'mars',               name_plural: 'marss'},
  {size: '12756000',    name_singular: 'earth',              name_plural: 'earths'},
  {size: '142984000',   name_singular: 'jupiter',            name_plural: 'jupiters'},
  {size: '1390000000',  name_singular: 'earth\'s sun',       name_plural: 'earth\'s suns'},
]
